eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  db:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/dhl_microservice?stringtype=unspecified
      password: root
      username: postgres
      database: dhl_microservice
      port: 5432
      dbHost: localhost

  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username

openapi:
  info:
    server: http://localhost:8082/self-service-template-microservice
