eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  config:
    template-url: http://localhost:6011/api/template
    cleansing-station-url: http://localhost:6011/api/cleansing-station
