server:
  port: 0
  servlet:
    contextPath: /self-service-file-microservice
spring:
  application:
    name: self-service-file-microservice
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 10000
      keepaliveTime: 5000
      maximumPoolSize: 20
      minimumIdle: 5
      pool-name: self-service-file-microservice
  devtools:
    restart:
      enabled: true
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
      enabled: true

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /swagger/api/v1/api-docs

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      example:
        base-config: shared

openapi:
  info:
    title: "SSP file Management Service API"
    version: "v_1.0"
    ownerName: "Akshay Adme"
    ownerEmail: "akshay.adme@nagarro.com"
    termsOfService: "http://dhl.io/terms/"
    licenseName: "Apache 2.0"
    licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"

http:
  security:
    allowRequests: /swagger/**,/swagger-ui/**,/v1/api/user-mgmt/**
