eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  db:
    datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
      password: rootuser
      username: c##cdcp_usr_mgmt
  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://20.219.56.2:30435/auth/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username

openapi:
  info:
    server: http://localhost:8082/self-service-oracle-template-microservice
