server:
  port: 0
  servlet:
    contextPath: /self-service-user-management-microservice

spring:
  application:
    name: self-service-user-management-microservice
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 10000
      keepaliveTime: 5000
      maximumPoolSize: 20
      minimumIdle: 5
      pool-name: self-service-user-management-microservice
  devtools:
    restart:
      enabled: true
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

springdoc:
  api-docs:
    path: /swagger/api/v1/api-docs

openapi:
  info:
    title: "SSP User Management Service API"
    version: "v_1.0"
    ownerName: "Akshay Adme"
    ownerEmail: "akshay.adme@nagarro.com"
    termsOfService: "http://dhl.io/terms/"
    licenseName: "Apache 2.0"
    licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"

http:
  security:
    allowRequests: /swagger/**,/swagger-ui/**,/v1/api/user-mgmt/**
